services:
  app:
    build: .
    depends_on:
      - db-sso
    environment:
      - CONFIG_PATH=./config/config.yaml

  db-sso:
    container_name: postgres-sso
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: new_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  migrations:
    build: .
    depends_on:
      - db-sso
    command: ./migrator -migrate


volumes:
  db_data: